### ISSUE TITLE
Newer versions of requirements

### ISSUE THREAD

**Issue by xybu** [jnrbsn/daemonocle#8]
Tons of bugs of psutil have been fixed since 2.1.1. See https://github.com/giampaolo/psutil/blob/master/HISTORY.rst
Could you update the requirement so that we use the latest psutil?

Same goes to click, the latest version of which is 3.3.

**Comment by Cediddi** [comment]
I guess the author abandoned this library. Somebody should take this lib over.

**Comment by xybu** [comment]
A cool library though.

**Comment by jnrbsn** [comment]
I have _**not**_ abandoned this project. I've been extremely busy the past few months, because I started a new job and moved to a new city 2000+ miles away. I have definitely been meaning to start working on this again soon now that my life is settling down a bit. My first priorities will be upgrading dependencies, adding unit tests and setting up Travis CI, and officially supporting Python 3.

**Comment by iromli** [comment]
@jnrbsn any news about upgrading dependencies? it would be nice if the dependencies aren't pinned to exact version. I have issue while trying to integrate this library with existing `click` v4.0 because `daemonocle` uses `click` v2.5. While there's no testcase yet, I can confirm that `daemonocle` works with latest `click` and `psutil`.

Regards.

**Comment by miohtama** [comment]
One should not pin down version numbers in a library as daemonocle. Currently this package doesn't play well with other packages from PyPi, as click and psutil are quite generic dependencies.

**Comment by miohtama** [comment]
Hi! As a temporary workaround I rolled out a fixed package. You can install it with:

     pip install --extra-index-url https://pypi.fury.io/uzQ6egqLUi1bcfHJehXv/miohtama/ daemonocle==0.8.1

**Comment by jnrbsn** [comment]
@xybu @Cediddi @iromli @miohtama: Sorry for the extremely delayed response. [Version 1.0 is now on PyPI](https://pypi.python.org/pypi/daemonocle). It has **NO pinned dependencies**. There are also many bug fixes, a new suite of unit tests with over 90% code coverage, and official support for Python 2.7, 3.3, 3.4, and 3.5. With this new release, I will be able to respond more quickly to pull requests and other issues. Once again, I'm sorry for the delay. Thank you for your interest in daemonocle.

**Comment by miohtama** [comment]
Thanks for the hard work! All green here now: https://pypi.python.org/pypi/pyramid-notebook/0.1.11 (though drone.io just stopped working)
